"use client";

import Link from "next/link";
import Logo from "@/components/Logo";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-claude-bg">
      {/* Navigation */}
      <nav className="fixed top-0 w-full bg-claude-bg/80 backdrop-blur-md border-b border-claude-border z-50">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/">
            <Logo size="md" />
          </Link>
          <div className="flex items-center gap-4">
            <Link href="/login" className="btn-ghost text-sm">
              Log in
            </Link>
            <Link href="/signup" className="btn-primary text-sm">
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="pt-32 pb-20 px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-4xl font-bold text-claude-text mb-2">Terms of Service</h1>
          <p className="text-claude-text-secondary mb-12">Last updated: January 25, 2026</p>

          <div className="prose prose-gray max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">1. Acceptance of Terms</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                By accessing or using TeamPost ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">2. Description of Service</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                TeamPost is an AI-powered LinkedIn content creation and scheduling platform. We help users generate professional LinkedIn posts through guided conversations and automatically post approved content to their LinkedIn accounts.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">3. Account Registration</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                To use the Service, you must create an account and provide accurate, complete information. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">4. LinkedIn Integration</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                By connecting your LinkedIn account, you authorize us to post content on your behalf. You retain full control over what gets posted and must approve all content before it is published. You are responsible for ensuring your use of the Service complies with LinkedIn's Terms of Service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">5. User Content</h2>
              <p className="text-claude-text-secondary leading-relaxed mb-4">
                You retain ownership of the content you create through the Service. By using the Service, you grant us a license to use, store, and process your content solely for the purpose of providing the Service. You are responsible for the content you post and agree not to:
              </p>
              <ul className="list-disc pl-6 text-claude-text-secondary space-y-2">
                <li>Post content that is unlawful, harmful, threatening, abusive, or defamatory</li>
                <li>Impersonate any person or entity</li>
                <li>Post spam or misleading content</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on the intellectual property rights of others</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">6. AI-Generated Content</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                Content generated by our AI is provided as suggestions. You are responsible for reviewing, editing, and approving all content before it is posted. We do not guarantee the accuracy, completeness, or appropriateness of AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">7. Pricing and Payment</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                Free accounts include 10 AI-generated posts. Paid subscriptions are billed monthly at $20 per user. Payments are processed securely through Stripe. You may cancel your subscription at any time, and cancellation will take effect at the end of your current billing period.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">8. Refund Policy</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                We offer refunds on a case-by-case basis. If you are unsatisfied with the Service, please contact us within 30 days of your purchase to request a refund.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">9. Termination</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                We reserve the right to suspend or terminate your account at any time for violation of these Terms or for any other reason at our sole discretion. Upon termination, your right to use the Service will immediately cease.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">10. Disclaimer of Warranties</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">11. Limitation of Liability</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, TEAMPOST SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICE.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">12. Changes to Terms</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                We may update these Terms from time to time. We will notify you of any material changes by posting the new Terms on this page. Your continued use of the Service after such changes constitutes acceptance of the new Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">13. Governing Law</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-claude-text mb-4">14. Contact Us</h2>
              <p className="text-claude-text-secondary leading-relaxed">
                If you have any questions about these Terms, please contact us at:{" "}
                <a href="mailto:rohan.pavuluri@gmail.com" className="text-accent-coral hover:underline">
                  rohan.pavuluri@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="py-12 px-6 border-t border-claude-border">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <span className="text-sm text-claude-text-secondary">
            © 2026 TeamPost. All rights reserved.
          </span>
          <div className="flex items-center gap-6 text-sm text-claude-text-secondary">
            <Link href="/privacy" className="hover:text-claude-text transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-claude-text transition-colors">Terms</Link>
            <a href="mailto:rohan.pavuluri@gmail.com" className="hover:text-claude-text transition-colors">Contact</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
